print('program pertama saya')
print('saya Amanda Puspita')
print('alamat saya Jelutung 2')
print('hobi saya bermain bulu tangkis')
print('saya berasal dari sekolah SMK 1 Payung')
print(' saya lahir tanggal 17 Agustus 2004')